### ISSUE TITLE
Some questions :)

### ISSUE THREAD

**Issue by Thibaud-Ardoin** [ykrist/darp-rf#1]
Hello, 

Thank you for sharing this code ! I would be interested in using this repo, but I'm not sure to understand how all this works. Therefore, I have some questions:
- Is there a specific solving algorithm you use here ? 
- Is there a paper available on Restricted Fragment Algorithm for the Dial-A-Ride Problem ?
- What is exactly Gurobi optimization doing in there?
- How do I use your script on another data source?

Thanks a lot for your help,
Best,
Thibaud

**Comment by ykrist** [comment]
Hi Thibaud,

The paper has accepted but is awaiting publication.  I have emailed you the manuscript.

The algorithm is centered on solving a relaxation of the DARP with Mixed Integer Linear Programming (this is where Gurobi comes in), and gradually tightening the relaxation with new inequalities on-the-fly (lazy constraints).  

 With regards to using different data... yeah I really didn't plan for that.  The hacky thing to do would be to simply modify the instances in `./data/DARP_cordeau`.  This directory is auto-extracted upon running the main script, you could do it manually with 
```bash
cd ./data/ && tar -Jxf compressed/DARP_cordeau
```  
In the `./data/DARP_cordeau` directory, there is a `readme.txt` that describes the format of the files.  Then, create your new instances this format, eg
```bash
cp a2-16.txt custom.txt 
```
To get the script to recognise this instance, its name (without file extention) needs to be in the `INDEX.txt`.  The line number (starting at 0) `INDEX.txt` will be the instance's "index".  This index is what is passed to the main script.
```bash
mv INDEX.txt INDEX.txt.old && echo "custom" > INDEX.txt
```      
Running the main script:
```bash
python darp_restricted_fragments.py 0
```
Output:
```
---------------------------------------------------------------------------------
                         Input Value                                             
---------------------------------------------------------------------------------
                        extend 0                                                 
                         index 0                                                 
                      instance custom                                            
                      ridetime 1                                                 
                         sdarp 0                                                 
...
```
The `--ridetime` and `--extend` parameters will modify the input instance by scaling the maximum ride time and time windows, respectively. See the `--help` flag on the main script for details.

**Comment by Thibaud-Ardoin** [comment]
Hi ykrist,

Thank you very much for you fast and complete response ! Congratulation for the publication and thank you for sharing all your great work.

I'll try your hacky solution to use my data and come back to you incase.

Best,
Thibaud
