### ISSUE TITLE
Balance time consumption and efficiency

### ISSUE THREAD

**Issue by Thibaud-Ardoin** [ykrist/darp-rf#2]
Hello,

Thanks again for all the great work !
On instances of a certain size your algo is taking some time to compile the results. For example the smallest Cordeau & Laporte 2003 dataset instance is d=3 and t=24 and it needs dozens of minutes to compile in such data size.

If I would like to have a faster results, would there be a way to alterate the solution's efficiency in order to spare compilation complexity ? And if yes, what are the means at my disposal ?

Thank you a lot for your help,
Best,
T.

**Comment by ykrist** [comment]
I'm assuming you're referring to the `R1a` instance from *A tabu search heuristic for the static multi-vehicle
dial-a-ride problem* (2003).  

These problems have loose time windows and/or ride times. This makes these problems difficult to solve for the RF method. The RF method is an exact algorithm and a lot of computational effort is put into proving optimality, whereas it sounds like you just want a decent solution.  In that case, I'd suggest using heuristic algorithm instead, like the tabu search of Cordeau and Laport.  Alternatively, constraint programming with Google OR tools - see the [Pickup-and-Delivery example](https://developers.google.com/optimization/routing/pickup_delivery).

You could also set a time limit directly with the `--timelimit` flag.  This should output the best solution found so far.

**Comment by Thibaud-Ardoin** [comment]
Yes, I understand that your solution is computational expressive because it is exact and looks for an optimal solution. 

> a lot of computational effort is put into proving optimality

Do you mean it take so long because it checks also the results with other methods ? If yes, would there be a way to remove all the annexe computation in order to get only the RF solution on a problem instance ?

> You could also set a time limit directly with the --timelimit flag. This should output the best solution found so far.

On what part of the algo does it set a limit ?

**Comment by Thibaud-Ardoin** [comment]
Ok, I just realize that in '_tabu search heuristic for the static multi-vehicle
dial-a-ride problem (2003)_' what causes such big computation time are the time and capacity contraints. 
Whereas, by restricting them such as in '_branch-and-cut algorithm for the dial-a-ride problem (2006)_' the computation time is drastically reduced.

**Comment by ykrist** [comment]
No, the code doesn't run other algorithms.  What I meant was that the optimal solution may be found early on, but has not yet been proven optimal through the lower bound.  

The time limit applies to the Branch-and-Cut part of the algorithm.  The fragment generation/network construction will always run, though for larger R-instances this can take some time.

Yeah, the two problem sets are pretty different.  The ones from the first paper (R instances) are typically used to benchmark heuristic and inexact algorithms.  The ones from the second paper (A and B instances) are usually used for exact algorithms.

**Comment by Thibaud-Ardoin** [comment]
Okay, I see.
Thanks for all the clarifications !

Best,
T.
